---
Name: ecommerce_delivery
Before: 'mysite/*'
After: 'framework/*','cms/*','ecommerce/*'
---
StoreAdmin:
  managed_models:
    - PickUpOrDeliveryModifierOptions

OrderModifierForm_Controller:
  allowed_actions:
    - PickUpOrDeliveryModifier
